spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

application:
  schedule:
    cron: "0 0/5 * * * ?"
  batch:
    chunkSize: 10000
  sftp:
    host: hostname
    port: 22
    user: ubuntu
    privateKey: classpath:sftp.ppk
    directory: /home/ubuntu

logging.level.org.apache.sshd: DEBUG