spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

application:
  schedule:
    cron: "0 0/5 * * * ?"
  batch:
    chunkSize: 10000
  sftp:
    host: 192.168.3.231
    port: 22
    user: stefan
    privateKey: classpath:id_rsa
    directory: /home/stefan

logging.level.org.apache.sshd: DEBUG